In [11]:
import inspect

def get_args_info(func):
    signature = inspect.signature(func)
    parameters = signature.parameters
    
    args = []
    kwargs = []
    
    for param in parameters.values():
        if param.default == inspect.Parameter.empty:
            args.append((param.name, param.annotation))
        else:
            kwargs.append((param.name, param.annotation, param.default))
    
    return {
        'name': func.__name__,
        'return_type': signature.return_annotation,
        'args': args,
        'kwargs': kwargs
    }

def add(a:int, b:int)->int:
    return a+b

result = get_args_info(add)

In [5]:
import dolphindb as ddb
import pandas as pd
import numpy as np

In [15]:
np.array(pd.date_range(start='2023-04-01 00:00:00', end='2023-04-01 12:00:00', freq='H'), dtype="datetime64[h]")


array(['2023-04-01T00', '2023-04-01T01', '2023-04-01T02', '2023-04-01T03',
       '2023-04-01T04', '2023-04-01T05', '2023-04-01T06', '2023-04-01T07',
       '2023-04-01T08', '2023-04-01T09', '2023-04-01T10', '2023-04-01T11',
       '2023-04-01T12'], dtype='datetime64[h]')

In [1]:
from factor_cal.utils.ddb_utils import s

In [4]:
a = s.database(dbPath="secondLevelDBV2")

In [10]:
arr = np.random.random((5, 3))
arr

array([[0.33011215, 0.4194965 , 0.06043669],
       [0.92729206, 0.37989337, 0.66282291],
       [0.09157675, 0.76370801, 0.71578019],
       [0.37210802, 0.43776648, 0.7650708 ],
       [0.83506207, 0.49147903, 0.08911886]])

In [12]:
arr.flatten(order='F')

array([0.33011215, 0.92729206, 0.09157675, 0.37210802, 0.83506207,
       0.4194965 , 0.37989337, 0.76370801, 0.43776648, 0.49147903,
       0.06043669, 0.66282291, 0.71578019, 0.7650708 , 0.08911886])

In [13]:
import numpy as np

# Define two one-dimensional arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Calculate the Cartesian product
cartesian_product = np.meshgrid(array1, array2)

# Print the result
print(cartesian_product)

[array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]]), array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])]


In [19]:
cartesian_product[0].flatten(or), cartesian_product[1].flatten()

(array([1, 2, 3, 1, 2, 3, 1, 2, 3]), array([4, 4, 4, 5, 5, 5, 6, 6, 6]))

In [18]:
np.meshgrid(array1, array2)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])]

In [5]:
a = {}
if not a:
    print("The dictionary is empty")
else:
    print("The dictionary is not empty")

bool(a)

The dictionary is empty


False

In [ ]:
import pickle

def read_large_pickle_file(file_path):
    with open(file_path, 'rb') as file:
        unpickler = pickle.Unpickler(file)
        while True:
            try:
                yield unpickler.load()
            except EOFError:
                break

file_path = 'path/to/your/file.pickle'
for data_chunk in read_large_pickle_file(file_path):
    # Process each data chunk here
    print(data_chunk)

In [1]:
import pandas as pd

# 创建一个DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Gender': ['F', 'M', 'M']}
df = pd.DataFrame(data)

df.shape

(3, 3)

In [ ]:
df['side'] = df['side'].astype(str)